import type { Flow } from '../types';
import { startFlow } from './start';
import { startseiteFlow } from './startseite';
import { orteFlow } from './orte';
import { naechteFlow } from './naechte';
import { zimmerFlow } from './zimmer';
import { bewertungFlow } from './bewertung';
import { attraktivitaetFlow } from './attraktivitaet';
import { filterFlow } from './filter';
import { bilderFlow } from './bilder';
import { ausstattungFlow } from './ausstattung';
import { karteFlow } from './karte';
import { themenFlow } from './themen';
import { europaFlow } from './europa';
import { fahrzeitFlow } from './fahrzeit';
import { regionsnameFlow } from './regionsname';
import { buchungFlow } from './buchung';
import { entwicklerFlow } from './entwickler';
import { ergebnisseFlow } from './ergebnisse';
import { finaleFlow } from './finale';
import { langsamFlow } from './langsam';
import { pflichtseitenFlow } from './pflichtseiten';
import { sucheFlow } from './suche';
import { suchrahmenFlow } from './suchrahmen';
import { warnungenFlow } from './warnungen';

export const flows: Flow[] = [startFlow, startseiteFlow, pflichtseitenFlow, suchrahmenFlow, orteFlow, naechteFlow, zimmerFlow, bewertungFlow, attraktivitaetFlow, filterFlow, bilderFlow, ausstattungFlow, karteFlow, themenFlow, europaFlow, fahrzeitFlow, regionsnameFlow, sucheFlow, ergebnisseFlow, finaleFlow, warnungenFlow, buchungFlow, entwicklerFlow, langsamFlow];
