// Pure renderers for the generated configuration outputs (used by the
// generator and by the drift test).
import type { ProductConfig } from './schema';

function hexToRgb(hex: string): [number, number, number] {
  const n = Number.parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function mix(hex: string, target: string, weight: number): string {
  const a = hexToRgb(hex);
  const b = hexToRgb(target);
  const out = a.map((v, i) => Math.round(v * (1 - weight) + (b[i] ?? 0) * weight));
  return `#${out.map((v) => v.toString(16).padStart(2, '0')).join('')}`;
}

export function renderConfigModule(config: ProductConfig): string {
  return [
    '// GENERATED by packages/config/src/bin/generate.ts from product.config.yaml.',
    '// Do not edit by hand: change product.config.yaml and run `npm run gen`.',
    "import type { ProductConfig } from '../schema';",
    '',
    `export const productConfig: ProductConfig = ${JSON.stringify(config, null, 2)};`,
    '',
  ].join('\n');
}

export function renderBrandCss(config: ProductConfig): string {
  const { colors, fonts } = config.brand;
  const scale: Array<[string, string, number]> = [
    ['50', '#ffffff', 0.92],
    ['100', '#ffffff', 0.84],
    ['200', '#ffffff', 0.68],
    ['300', '#ffffff', 0.48],
    ['400', '#ffffff', 0.24],
    ['500', '#ffffff', 0],
    ['600', '#000000', 0.12],
    ['700', '#000000', 0.26],
    ['800', '#000000', 0.42],
    ['900', '#000000', 0.58],
  ];
  const lines = [
    '/* GENERATED by packages/config/src/bin/generate.ts from product.config.yaml. Do not edit. */',
    '@theme {',
    `  --font-sans: ${fonts.sans};`,
    ...scale.map(([step, target, w]) => `  --color-brand-${step}: ${mix(colors.primary, target, w)};`),
    `  --color-brand-contrast: ${colors.primary_contrast};`,
    `  --color-accent-500: ${colors.accent};`,
    `  --color-accent-100: ${mix(colors.accent, '#ffffff', 0.84)};`,
    `  --color-bargain-600: ${colors.bargain};`,
    `  --color-bargain-50: ${mix(colors.bargain, '#ffffff', 0.92)};`,
    `  --color-bargain-100: ${mix(colors.bargain, '#ffffff', 0.84)};`,
    `  --color-warning-600: ${colors.warning};`,
    `  --color-warning-50: ${mix(colors.warning, '#ffffff', 0.92)};`,
    `  --color-warning-100: ${mix(colors.warning, '#ffffff', 0.84)};`,
    '}',
    '',
  ];
  return lines.join('\n');
}
