// Build-time compilation of the bundle JSON schemas into standalone
// validator code (architektur.md 9.1: Workers forbid runtime code generation).
// Ajv's standalone output references two runtime helpers via require(); they
// are inlined here so the module is plain ESM without dependencies.
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import type { RawBundle } from './load';

const RUNTIME_HELPERS: Record<string, string> = {
  'ajv/dist/runtime/ucs2length': `function __ucs2length(str) {
  let length = 0;
  for (let pos = 0; pos < str.length; length++) {
    const value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < str.length && (str.charCodeAt(pos) & 0xfc00) === 0xdc00) pos++;
  }
  return length;
}`,
  'ajv/dist/runtime/equal': `function __equal(a, b) {
  if (a === b) return true;
  if (a && b && typeof a === 'object' && typeof b === 'object') {
    if (Array.isArray(a) !== Array.isArray(b)) return false;
    if (Array.isArray(a)) return a.length === b.length && a.every((v, i) => __equal(v, b[i]));
    const ka = Object.keys(a);
    return ka.length === Object.keys(b).length && ka.every((k) => Object.prototype.hasOwnProperty.call(b, k) && __equal(a[k], b[k]));
  }
  return a !== a && b !== b;
}`,
};

export function validatorName(skillId: string, kind: 'input' | 'output'): string {
  return `${skillId.replace(/^reiseplaner\./, '').replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())}${kind === 'input' ? 'Input' : 'Output'}`;
}

export interface CompiledModule {
  code: string;
  names: string[];
}

export function compileValidators(bundles: RawBundle[]): CompiledModule {
  const ajv = new Ajv({ code: { source: true, esm: true, lines: true }, allErrors: true, strict: true });
  const exportsMap: Record<string, string> = {};
  for (const b of bundles) {
    for (const kind of ['input', 'output'] as const) {
      const schema = kind === 'input' ? b.inputSchema : b.outputSchema;
      const id = `${b.manifest.id}/${b.manifest.version}/${kind}`;
      if (schema.$id !== id) throw new Error(`${b.manifest.id}: ${kind} schema $id must be "${id}"`);
      ajv.addSchema(schema);
      exportsMap[validatorName(b.manifest.id, kind)] = id;
    }
  }
  let code = standaloneCode(ajv, exportsMap);
  const used = new Set<string>();
  code = code.replace(/require\("([^"]+)"\)\.default/g, (_, mod: string) => {
    const helper = RUNTIME_HELPERS[mod];
    if (!helper) throw new Error(`standalone validator needs unsupported runtime ${mod}; avoid that keyword/format`);
    used.add(mod);
    return mod.endsWith('ucs2length') ? '__ucs2length' : '__equal';
  });
  if (/\brequire\(/.test(code)) throw new Error('standalone validator still contains require()');
  const helpers = [...used].sort().map((m) => RUNTIME_HELPERS[m]).join('\n');
  return {
    code: `// Generated by npm run skills:build from packages/skills/bundles — do not edit.\n/* eslint-disable */\n${helpers}\n${code.replace(/^"use strict";/, '')}\n`,
    names: Object.keys(exportsMap),
  };
}
