// Bundle table generated by `npm run skills:build` (Workers cannot read files
// at runtime).
import { bundles } from './generated/bundles';
import { UnknownSkillError, type SkillBundle } from './types';

export function getSkill(id: string): SkillBundle {
  const bundle = bundles[id];
  if (!bundle) throw new UnknownSkillError(id);
  return bundle;
}

export function skillIds(): string[] {
  return Object.keys(bundles).sort();
}
