// `npm run dev`: local stack in one command.
// 1. Creates packages/worker/.dev.vars with random local secrets if missing.
// 2. Starts the local database (PGlite on 127.0.0.1:54329) unless one is
//    already running (`npm run db:local` in another terminal).
// 3. Runs Vite with the Cloudflare plugin (SPA + Worker in workerd).
import { spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { createConnection } from 'node:net';
import { resolve } from 'node:path';
import { DEFAULT_LOCAL_DB_PORT, repoRoot, startLocalDb } from '@reiseplaner/db/node';

const devVarsPath = resolve(repoRoot, 'packages/worker/.dev.vars');
if (!existsSync(devVarsPath)) {
  const secret = () => randomBytes(32).toString('base64url');
  writeFileSync(
    devVarsPath,
    [
      '# Generated by `npm run dev` with random local values. Not used outside this machine.',
      `SIGNING_KEY=${secret()}`,
      `IP_HASH_SALT=${secret()}`,
      `ALTCHA_HMAC_KEY=${secret()}`,
      `OPS_HB_TOKEN=${secret()}`,
      '',
    ].join('\n'),
  );
  console.log('dev: created packages/worker/.dev.vars with random local secrets');
}

function portInUse(port: number): Promise<boolean> {
  return new Promise((done) => {
    const socket = createConnection({ port, host: '127.0.0.1' });
    socket.once('connect', () => {
      socket.destroy();
      done(true);
    });
    socket.once('error', () => done(false));
  });
}

const dbPort = Number(process.env.DB_PORT ?? DEFAULT_LOCAL_DB_PORT);
let stopDb: (() => Promise<void>) | undefined;
if (await portInUse(dbPort)) {
  console.log(`dev: using the database already listening on 127.0.0.1:${dbPort}`);
} else {
  const dataDir = process.env.REISEPLANER_DATA_DIR;
  const local = await startLocalDb({ port: dbPort, ...(dataDir ? { dataDir } : {}) });
  stopDb = local.stop;
}

// Point the Worker's Hyperdrive binding at this database (wrangler reads
// CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_<BINDING> in local dev).
const vite = spawn('npx', ['vite', ...process.argv.slice(2)], {
  cwd: resolve(repoRoot, 'packages/web'),
  stdio: 'inherit',
  env: {
    ...process.env,
    CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: `postgres://postgres:postgres@127.0.0.1:${dbPort}/postgres`,
  },
});

let stopping = false;
const shutdown = async (code = 0) => {
  if (stopping) return;
  stopping = true;
  vite.kill('SIGTERM');
  await stopDb?.();
  process.exit(code);
};
vite.on('exit', (code) => void shutdown(code ?? 0));
process.on('SIGINT', () => void shutdown(0));
process.on('SIGTERM', () => void shutdown(0));
